
export const NETWORKSTATUS = "NETWORKSTATUS"

export const SET_TOGGLE_SIDEBAR = 'SET_TOGGLE_SIDEBAR'

export const SET_VISITED_VIEWS = 'SET_VISITED_VIEWS'

export const SET_ROUTERS = 'SET_ROUTERS'

export const SET_ADD_ROUTERS = 'SET_ADD_ROUTERS'

export const SET_USER_ACCESSROUTERS = 'SET_USER_ACCESSROUTERS'

export const SET_USER_TYPE = 'SET_USER_TYPE'

export const SET_USER_CODE = 'SET_USER_CODE'

export const SET_EMP_NO = 'SET_EMP_NO'

export const SET_COMPANY_CODE = 'SET_COMPANY_CODE'

export const SET_TOKEN = 'SET_TOKEN'

export const SET_COMPANYORSYSTEM = 'SET_COMPANYORSYSTEM'

export const SET_SETTING = 'SET_SETTING'

export const SET_STATUS = 'SET_STATUS'

export const SET_NAME = 'SET_NAME'

export const SET_AVATAR = 'SET_AVATAR'

export const SET_GENERATE = 'SET_GENERATE'

export const SET_ALREADY_UPLOAD_FILE = 'SET_ALREADY_UPLOAD_FILE'

export const SET_ALREADY_UPLOAD_DETAIL = 'SET_ALREADY_UPLOAD_DETAIL'

export const SET_LOADING = 'SET_LOADING'

export const SET_SCHEME_CODE = 'SET_SCHEME_CODE'

export const SET_CURRENT_FIELD = 'SET_CURRENT_FIELD'

export const SET_CURRENT_FIELDS = 'SET_CURRENT_FIELDS'

export const SET_NODE_OBJ = 'SET_NODE_OBJ'

export const SET_QUILLEDITORTOOLNum = 'SET_QUILLEDITORTOOLNum'

export const SET_FLOW_FUNCTIONROLE = 'SET_FLOW_FUNCTIONROLE'

export const SET_FLOW_EDITORValue = 'SET_FLOW_EDITORValue'

export const SET_isPublic = 'SET_isPublic'

export const SET_AUTHORITY_PAGECODE = 'SET_AUTHORITY_PAGECODE'

export const SET_FLOWRULESCAN_FLAG = 'SET_FLOWRULESCAN_FLAG'

export const SET_COMPANYROLESCAN_FLAG = 'SET_COMPANYROLESCAN_FLAG'

export const SET_FLOW_CURRENTOBJ = 'SET_FLOW_CURRENTOBJ'

export const SET_FLOW_CURRENTFLOWFORMOBJ = 'SET_FLOW_CURRENTFLOWFORMOBJ'

export const SET_FLOW_CURRENTTAB = 'SET_FLOW_CURRENTTAB'

//----------------------pa 模块----------//

export const SET_CURRENTPAGECODE = 'SET_CURRENTPAGECODE'

export const SET_CURRENTTEMPLATEPAGECODE = 'SET_CURRENTTEMPLATEPAGECODE'

export const SET_CURRENTTEMPLATECODE = 'SET_CURRENTTEMPLATECODE'

export const SET_ALREADYUPLOADFILE = 'SET_ALREADYUPLOADFILE'

export const SET_CURRENTEMPOBJ = 'SET_CURRENTEMPOBJ'

export const SET_CURRENTTABITEM = 'SET_CURRENTTABITEM'

export const SET_CONTRACTMANAGEPAGECODE = "SET_CONTRACTMANAGEPAGECODE"

export const SET_BATCHEXPORTORIMPORTEMP = "SET_BATCHEXPORTORIMPORTEMP"

export const SET_ISEMPORCONTRACT = "SET_ISEMPORCONTRACT"